alutracer/urls.py
from django.urls import path

from .views import (
        PersonalInfoDetailView,
        PersonalInfoCreateView
    )
app_name='alutracer'

urlpatterns = [
    path('create/', PersonalInfoCreateView.as_view(), name='personal-info-create'),
    path('<slug:slug>/', PersonalInfoDetailView.as_view(), name='personal-info-detail'),
    # path('course', course_list, name='course-list'),
    # path('choice', choice_list, name='choice-list'),
    # path('personal-information', personal_information_list, name='personal-information-list'),
    # path('question', question_list, name='question-list'),
    # path('course/<str:pk>', course_detail, name='course-detail'),
    # path('choice/<str:pk>', choice_detail, name='choice-detail'),
    # path('personal-information/<str:pk>', personal_information_detail, name='personal-information-detail'),
    # path('question/<str:pk>', question_detail, name='question-detail')
]

ndmc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from alutracer.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('oauth', include('social_django.urls', namespace='social')),
    #App Urls
    path('pdfdrive/', include('pdfdrive.urls', namespace='pdfdrive')),
    path('alutracer/', include('alutracer.urls', namespace='alutracer')),
    path('user/', include('account.urls', namespace='user'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdfdrive/urls.py
from django.urls import path
from . import views

app_name='pdfdrive'
urlpatterns = [
    path('', views.PostView.as_view(), name='post'),
    path('<title>/', views.PostDetailView.as_view(), name='detail'),
#    path('post/', views.PdfUploadView.as_view(), name='post')
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang=en>
  <head> 
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'img/ndmc-logo.jpeg' %}" type="image/vnd.microsoft.icon">
    <title>NDMC Alumni Tracer and Research Repository</title>
    {% include 'snippets/css.html'%}
  </head>
  <body>
    <header>
      <!-- Start nav -->
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">
              <img alt="Brand" src="{% static '/img/favicon.ico' %}">
            </a>
            <a class="navbar-brand navbar-resize" href="{% url 'home' %}">NDMC Alumni Tracer and Research Repository</a>
          </div>
          <div id="navbar" class="navbar-collapse navbar-right collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'alutracer:personal-info-create' %}">Alumni Tracer</a></li>
              <li><a href="#">Research Repository</a></li>
            </ul>
            <button type="button" class="btn btn-sign-in navbar-btn navbar-right btn-layout button" data-toggle="modal" data-target="#myModal">
              <span>Sign in</span>
            </button>
          </div>
        </div>
      </nav>
      <!-- End nav -->
      <!-- Start modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Sign in</h4>
            </div>
            <div class="modal-body">
              <form>
                <div class="form-group">
                  <label for="exampleInputUsername">Username</label>
                  <input type="username" class="form-control" id="exampleInputUsername" placeholder="Username">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <div class="footer-modal-social">
                <a href="{% url 'social:begin' 'facebook' %}"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
                <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
              </div>
              <button type="button" class="btn btn-sign-in navbar-btn navbar-right btn-layout button footer-modal-btn" data-dismiss="modal">
                <span>Close</span>
              </button>
              <button type="submit" class="btn btn-sign-in navbar-btn navbar-right btn-layout button footer-modal-btn">
                <span>Login</span>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End modal -->
    </header>
    {% block content %}{% endblock content %}
    <div class="footer">
      <div id="button"></div>
      <div id="container">
        <div class="social-layout">
          <a href="{% url 'social:begin' 'facebook' %}"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
          <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
          <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
        </div>
        <div id="cont">
          <img alt="Brand" class="footer-logo" src="{% static 'img/ndmc-logo.jpeg' %}">
          <div class="footer_center">
            <h3>NDMC</h3>
            <p>Alumni Tracer and Research Repository</p>
            <p>&copy; Copyright <script>document.write(Date().split(' ')[3])</script></p>
          </div>
        </div>
      </div>
    </div>
    <!-- back to top -->
    <a href="#0" class="cd-top js-cd-top">Top</a>
    {% include 'snippets/js.html' %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
  <!-- Start Carousel
  ================================================== -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      {% for id in index %}
        <li data-target="#myCarousel" data-slide-to="{{ id.id }}" class="{% if forloop.first %} active {% endif %}"></li>
      {% endfor %}
    </ol>
    <div class="carousel-inner" role="listbox">
      {% for post in index %}
        <div class="item">
          <img class="first-slide" src="{{ MEDIA_URL }}{{ post.cover_photo.url }}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>{{ post.title }}</h1>
              <p>{{ post.description }}</p>
              <p><a class="btn animated-button thar-four" href="https://getbootstrap.com/docs/3.3/examples/carousel/#" role="button">Sign up</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <a class="left carousel-control" href="https://getbootstrap.com/docs/3.3/examples/carousel/#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="https://getbootstrap.com/docs/3.3/examples/carousel/#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div><!-- /.carousel -->
  <!-- Start card -->
  <div class="container fade-up fade-ani fade">
    <hr class="featurette-divider">
    <div class="row">
      {% for card in pdf_list %}
        <div class="col-lg-4">
          <h2>{{ card.title }}</h2>
          <p>{{ card.description }}</p>
          <button type="button" class="btn button btn-sign-in" onclick="location.href='{% url "pdfdrive:detail" card.title%}'" >
            <span>View Details</span>
          </button>
        </div>
      {% endfor %}
    </div>
    <hr class="featurette-divider">
  </div><!-- End card -->
  <!-- Start Parallax -->
  {% for parallx in parallax %}
    <div class="parallax fade-down fade-ani fade" style="background-image: url({{ MEDIA_URL }}{{ parallx.parallax_1.url }});">
      <div class="container">
        <div class="parallax-caption float-right">
          <h1>{{ parallx.parallax_1_heading }}</h1>
          <p>{{ parallx.parallax_1_content}}</p>
        </div>
      </div>
    </div>
  {% endfor %}
  <!-- Start Thumbnail -->
  <div class="container sectional-wrapper fade-right fade-ani fade" >
    <div class="row" >
      <div class="col-md-12" >
         <div class="dynamicDiv" id="dd.0.2.0" >
            <div class="row" >
               <div class="col-md-12 pagingBorder" >
                  <div id="theImageGrid" >
                    <ul class="row imagegrid" id="imagegrid" >
                      {% for thumbn in thumbnail %}
                        <li class="col-xs-12 col-sm-6 col-md-4" id="22" >
                          <div class="imgHolder" >
                            <div class="fauxCrop" >
                              <a href="" ><img src="{{ MEDIA_URL }}{{ thumbn.thumbnail.url }}" ></a>
                            </div>
                          </div>
                          <div class="clearfix" ></div>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- End Thumbnail -->
  {% for parallx in parallax %}
    <div class="parallax1 fade-left fade-ani fade" style="background-image: url({{ MEDIA_URL }}{{ parallx.parallax_2.url }});">
      <div class="container">
        <div class="parallax-caption center">
          <h2>{{ parallx.parallax_2_heading}}</h2>
          <p>{{ parallx.parallax_2_content}}</p>
        </div>
      </div>
    </div><!-- End Parallax -->
  {% endfor %}
{% endblock content %}

templates/pdf_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %} 
<head>
  <link rel="stylesheet" href="{% static 'css/pdf.css' %}">
</head>
 
  <div class="wrapper">
    <nav id="sidebar">
      <div class="sidebar-header">

      <h3 class="title"><a target="_blank" href="img_forest.jpg">
      <img src="{{ MEDIA_URL }}{{ post.cover.url }}" alt="{{post.title}}">
    </a> </h3>
      </div>
      <ul class="list-unstyled components">
        <p>{{post.title}}</p>
        <li class="active">
          <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">Author: {{post.author.lastname}} {{post.author.firstname}}</a>
          <ul class="collapse list-unstyled" id="homeSubmenu">
            <li><p>Course: {{post.author.course}}</p></li>
            <li><a href="#">Home 2</a></li>
            <li><a href="#">Home 3</a></li>
          </ul>
        </li>
          <li>
            <a href="#">About</a>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">Pages</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li><a href="#">Page 1</a></li>
              <li><a href="#">Page 2</a></li>
              <li><a href="#">Page 3</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Portfolio</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
      </ul>
      <ul class="list-unstyled CTAs">
        <li><a href="" class="download">Download Research</a></li>
        <li><a href="" class="article">Back to article</a></li>
      </ul>
    </nav>
    <div class="container">
      <div id="content">
        <nav class="navbars navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" id="sidebarCollapse" class="navbars-btn">
              <span></span>
              <span></span>
              <span></span>
              </button>
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only"> </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <div class="search">
                  <form class="form-inline">
                    <div class="form-group">
                      <div class="input-group">
                        <input type="text" class="form-control " aria-label="..." placeholder="Search ...">
                        <div class="input-group-btn">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All categories <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">Wszystkie kategorie</a>
                            </li>
                            <li><a href="#">Another action</a>
                            </li>
                            <li><a href="#">Something else here</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a>
                            </li>
                          </ul>
                          <button type="submit" class="btn btn-default">
                            <i class="fa fa-search"></i>
                          </button>
                        </div>
                        <!-- /btn-group -->
                      </div>
                      <!-- /input-group -->
                    </div>
                  </form>
                </div>
             </div>
          </div>
        </nav> 
          <div class="pdf">        
            <embed src="{{post.file.url}}" width="100%" height="520" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html" background-color="0xFF525659"top-toolbar-height="220" full-frame="200" internalinstanceid="2100">
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}